---
- hosts: aws
  become: yes

  vars:
    docker_image: gabby1000/minipay-ui:latest
    cert_email: "gabrielakib35@gmail.com"

  tasks:
      - name: Update cache
        apt:
          update_cache: yes
          cache_valid_time: 3600

      - name: Install required Packages
        apt:
          name:
            - docker.io
            - nginx
            - certbot
            - python3-certbot-nginx
            - python3-pip
            - python3-docker
          update_cache: yes
          state: present

      - name: Start Docker
        service:
          name: docker
          state: started
          enabled: yes

      - name: Pull Docker Image
        community.docker.docker_image:
          name: "{{ docker_image }}"
          source: pull

      - name: Run Docker Container
        community.docker.docker_container:
          name: minipay-ui
          image: "{{ docker_image }}"
          state: started
          restart_policy: always
          recreate: true
          pull: always
          published_ports:
            - "3000:3000"
